# -*- coding: utf-8 -*-
"""The ABMF-required JHUSOM CV taxonomy. Levels: 1 = ALL CAPS section, 2/3/4 = nested headings."""
TAXONOMY = [
 (1,'DEMOGRAPHIC AND PERSONAL INFORMATION',''),
 (2,'Current Appointments','in chronological order, earliest first by start date under each subcategory'),
 (3,'University',''),(3,'Hospital',''),(3,'Other',''),
 (2,'Personal Data',''),
 (3,'Business Address',''),(3,'Tel',''),(3,'Fax (optional)',''),(3,'E-mail',''),

 (1,'EDUCATION AND TRAINING','in chronological order, earliest first by start date under each subcategory'),
 (2,'Undergraduate',''),(2,'Doctoral/graduate',''),(2,'Postdoctoral (Internship, residency, fellowship, etc.)',''),

 (1,'PROFESSIONAL EXPERIENCE','in chronological order, earliest first'),

 (1,'PUBLICATIONS','in chronological order, earliest first, under each subcategory'),
 (2,'Original Research [OR]','ONLY peer-reviewed, PubMed-indexed research publications are permitted here'),
 (2,'Review Articles [RA]',''),
 (2,'Case Reports [CR]',''),
 (2,'Book Chapters, Monographs [BC]',''),
 (2,'Books, Textbooks [BK]',''),
 (2,'Editorials [ED]',''),
 (2,'Guidelines/Protocols, Consensus Statement, Expert Opinion, Consortium Articles [GL]',''),
 (2,'Letters, Correspondence [LT]',''),
 (2,'Other Publications',''),
 (3,'Clinical Stories or Memoirs [CS]',''),
 (3,'Creative Writing [CW]',''),
 (3,'Methods and Techniques, "How I Do It" articles [MT]',''),
 (3,'Opinions, Perspectives, Political Commentary, Advocacy, Essays [OP]',''),
 (3,'Original Research, other (not peer reviewed and/or not indexed) [RO]',''),
 (3,'Proceedings Reports [PR]',''),
 (3,'Published Curricula, Learner Assessment Tools, Educational Evaluations, Assessment/Evaluation Instruments [PC]',''),
 (3,'White Papers [WP]',''),
 (3,'Media Releases or Interviews [MR]',''),
 (3,'Other Media [OM]',''),

 (1,'FUNDING','in chronological order, earliest first by start date under each subcategory'),
 (2,'EXTRAMURAL Funding','show as Current, Pending, Previous under each subcategory'),
 (3,'Research Extramural Funding',''),(3,'Educational Extramural Funding',''),
 (3,'Clinical Extramural Funding',''),(3,'System Innovation or Quality Improvement Extramural Funding',''),
 (3,'Other Extramural Funding, including philanthropy',''),
 (2,'INTRAMURAL Funding','show as Current, Pending, Previous under each subcategory'),
 (3,'Research Intramural Funding',''),(3,'Educational Intramural Funding',''),
 (3,'Clinical Intramural Funding',''),(3,'System Innovation or Quality Improvement Intramural Funding',''),
 (3,'Other Intramural Funding',''),

 (1,'CLINICAL ACTIVITIES',''),
 (2,'Clinical Focus','up to 100 words: narrative, bulleted accomplishments, or key words'),
 (2,'Certification',''),
 (3,'Medical, other state/government licensure',''),(3,'Boards, other specialty certification',''),
 (2,'Clinical (Service) Responsibilities',''),
 (2,'Clinical Productivity',''),
 (2,'Clinical Draw from outside local/regional area',''),
 (2,'Membership in or examiner for specialty board',''),
 (2,'Clinical Program Building / Leadership',''),
 (2,'Clinical Demonstration Activities to external audience, on or off campus',''),
 (2,'Development of nationally/internationally recognized clinical standard of care',''),

 (1,'EDUCATIONAL ACTIVITIES','in chronological order, earliest first by start date under each subcategory'),
 (2,'Educational Focus',''),
 (2,'Teaching',''),
 (3,'Classroom instruction',''),(4,'JHMI/Regional',''),(4,'National',''),(4,'International',''),
 (3,'Clinical instruction',''),(4,'JHMI/Regional',''),(4,'National',''),(4,'International',''),
 (3,'CME instruction',''),(4,'JHMI/Regional',''),(4,'National',''),(4,'International',''),
 (3,'Workshops /seminars',''),(4,'JHMI/Regional',''),(4,'National',''),(4,'International',''),
 (2,'Mentoring','list only mentees who received substantive and sustained mentoring'),
 (3,'Pre-doctoral Advisees /Mentees',''),(3,'Post-doctoral Advisees /Mentees',''),(3,'Thesis committees',''),
 (2,'Educational Program Building / Leadership',''),
 (2,'Educational Demonstration Activities to external audiences, on or off campus',''),

 (1,'RESEARCH ACTIVITIES','in chronological order, earliest first by start date under each subcategory'),
 (2,'Research Focus',''),
 (2,'Research Program Building / Leadership',''),
 (2,'Research Demonstration Activities to external audience, on or off campus',''),
 (2,'Inventions, Patents, Copyrights',''),
 (2,'Technology Transfer Activities',''),

 (1,'SYSTEM INNOVATION AND QUALITY IMPROVEMENT ACTIVITIES','indicate None or Not Applicable and delete the subcategories if empty; do not duplicate activities shown above'),
 (2,'System Innovation Focus',''),
 (2,'System Innovation and Quality Improvement efforts within JHMI',''),
 (2,'System Innovation and Quality Improvement efforts outside of JHMI',''),
 (2,'System Innovation and Quality Improvement Program Building/Leadership',''),

 (1,'ORGANIZATIONAL ACTIVITIES','in chronological order, earliest first by start date under each subcategory'),
 (2,'Institutional Administrative Appointments',''),
 (2,'Editorial Activities',''),
 (3,'Editorial Board appointments',''),(3,'Journal peer review activities',''),
 (3,'Other peer review activities [non medico-legal]',''),
 (2,'Advisory Committees, Review Groups/Study Sections',''),
 (2,'Professional Societies',''),
 (2,'Conference Organizer',''),(3,'JHMI/Regional',''),(3,'National',''),(3,'International',''),
 (2,'Session Chair',''),(3,'JHMI/Regional',''),(3,'National',''),(3,'International',''),
 (2,'Consultantships',''),

 (1,'RECOGNITION','in chronological order, earliest first by start date under each subcategory'),
 (2,'Awards, Honors',''),
 (2,'Invited Talks',''),(3,'JHMI/Regional',''),(3,'National',''),(3,'International',''),
 (2,'Visiting Professorships',''),

 (1,'OTHER PROFESSIONAL ACCOMPLISHMENTS (Optional)','the entire section is optional'),
 (2,'Posters (optional)',''),
 (2,'Oral/Podium Presentations (optional)',''),
 (2,'Military Service (optional)',''),
 (2,'Community Services (optional)',''),
 (2,'Humanitarian Activities (optional)',''),
 (2,'Philanthropic Activities (optional)',''),
 (2,'Other (optional)',''),
]
