import { resolveFormat } from "../format-registry";
import type { McpServerDefinition } from "../schemas";
import { isStdioServer } from "../schemas";
import { renderTemplate } from "../template-engine";
import type { HarnessCapabilityName } from "./capabilities";
import { applyDegradation } from "./degradation";
import type {
	AdapterError,
	AdapterWarning,
	HarnessAdapter,
	OutputFile,
} from "./types";

/** Codex's default combined project-instructions budget. */
export const CODEX_PROJECT_DOC_MAX_BYTES = 32 * 1024;

function utf8ByteLength(value: string): number {
	return new TextEncoder().encode(value).byteLength;
}

/** TOML string literal — escape backslashes and double quotes. */
function tomlString(value: string): string {
	return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** TOML dotted-table key segment. */
function tomlKey(value: string): string {
	return /^[A-Za-z0-9_-]+$/.test(value) ? value : tomlString(value);
}

/** TOML inline array of strings. */
function tomlStringArray(values: string[]): string {
	return `[${values.map((v) => tomlString(v)).join(", ")}]`;
}

/** TOML inline table of string env vars. */
function tomlEnvTable(env: Record<string, string>): string {
	const pairs = Object.entries(env).map(([k, v]) => `${k} = ${tomlString(v)}`);
	return `{ ${pairs.join(", ")} }`;
}

/**
 * Serialize canonical MCP server definitions into Codex `config.toml` form.
 * Codex registers servers under `[mcp_servers.<name>]` tables.
 */
function buildCodexMcpToml(servers: McpServerDefinition[]): string {
	const blocks: string[] = [
		"# Generated by Kanon — merge into ~/.codex/config.toml or .codex/config.toml",
	];
	for (const server of servers) {
		const lines = [`[mcp_servers.${tomlKey(server.name)}]`];
		if (isStdioServer(server)) {
			lines.push(`command = ${tomlString(server.command)}`);
			if (server.args.length > 0) {
				lines.push(`args = ${tomlStringArray(server.args)}`);
			}
			if (Object.keys(server.env).length > 0) {
				lines.push(`env = ${tomlEnvTable(server.env)}`);
			}
		} else {
			// URL-based (SSE / streamable HTTP) servers.
			lines.push(`url = ${tomlString(server.url)}`);
			if (server.env && Object.keys(server.env).length > 0) {
				lines.push(`env = ${tomlEnvTable(server.env)}`);
			}
		}
		if (server.timeout) {
			lines.push(`startup_timeout_ms = ${server.timeout}`);
		}
		blocks.push(lines.join("\n"));
	}
	return `${blocks.join("\n\n")}\n`;
}

export const codexAdapter: HarnessAdapter = (
	artifact,
	templateEnv,
	context?,
) => {
	const files: OutputFile[] = [];
	const warnings: AdapterWarning[] = [];
	const errors: AdapterError[] = [];
	const degradedSections: string[] = [];

	// Capability degradation checks
	if (context) {
		const checks: Array<{
			capability: HarnessCapabilityName;
			hasFeature: boolean;
		}> = [
			{ capability: "hooks", hasFeature: artifact.hooks.length > 0 },
			{ capability: "mcp", hasFeature: artifact.mcpServers.length > 0 },
			{ capability: "workflows", hasFeature: artifact.workflows.length > 0 },
		];
		for (const { capability, hasFeature } of checks) {
			if (!hasFeature) continue;
			const entry = context.capabilities[capability];
			if (entry.support === "full") continue;
			const degradation = applyDegradation(
				entry.degradation ?? "inline",
				capability,
				artifact,
				"codex",
			);
			warnings.push(...degradation.warnings);
			if (context.strict) {
				warnings.push({
					artifactName: artifact.name,
					harnessName: "codex",
					message: `Strict mode: capability ${capability} is degraded for harness codex`,
				});
			}
			if (degradation.inlineText) {
				degradedSections.push(degradation.inlineText);
			}
		}
	}

	const harnessConfig = (artifact.frontmatter as Record<string, unknown>)[
		"harness-config"
	] as Record<string, unknown> | undefined;
	const codexConfig = (harnessConfig?.codex ?? {}) as Record<string, unknown>;
	const { format } = resolveFormat("codex", codexConfig);
	const skillName = artifact.name;
	const renderContext = {
		artifact,
		degradedSections,
	};

	if (format === "skill") {
		// Native Codex skill discovery path + always-loaded AGENTS.md pointer.
		const skillContent = renderTemplate(
			templateEnv,
			"codex/skill.md.njk",
			renderContext,
		);
		files.push({
			relativePath: `.agents/skills/${skillName}/SKILL.md`,
			content: skillContent,
		});

		// Workflow phase files live under references/ for progressive disclosure.
		for (const wf of artifact.workflows) {
			files.push({
				relativePath: `.agents/skills/${skillName}/references/${wf.filename}`,
				content: wf.content,
			});
		}

		const pointerContent = renderTemplate(
			templateEnv,
			"codex/agents-pointer.md.njk",
			renderContext,
		);
		files.push({ relativePath: "AGENTS.md", content: pointerContent });
	} else {
		// "agents-md": a repo-wide AGENTS.md carrying the full body.
		const agentsContent = renderTemplate(
			templateEnv,
			"codex/agents-md.md.njk",
			renderContext,
		);
		files.push({ relativePath: "AGENTS.md", content: agentsContent });
	}

	// MCP servers → .codex/config.toml
	if (artifact.mcpServers.length > 0) {
		files.push({
			relativePath: ".codex/config.toml",
			content: buildCodexMcpToml(artifact.mcpServers),
		});
	}

	// Codex has no canonical event-hook system (only the `notify` shell hook),
	// so declarative hooks are skipped.
	if (artifact.hooks.length > 0) {
		warnings.push({
			artifactName: artifact.name,
			harnessName: "codex",
			message:
				"Codex has no declarative event-hook system; hook definitions were rendered as manual guidance",
		});
	}

	const agentsFile = files.find((file) => file.relativePath === "AGENTS.md");
	if (agentsFile) {
		const size = utf8ByteLength(agentsFile.content);
		if (size > CODEX_PROJECT_DOC_MAX_BYTES) {
			const message =
				`AGENTS.md is ${size} bytes, exceeding Codex's default combined ` +
				`project_doc_max_bytes limit of ${CODEX_PROJECT_DOC_MAX_BYTES} bytes. ` +
				"Use harness-config.codex.format: skill or split instructions across nested directories.";
			warnings.push({
				artifactName: artifact.name,
				harnessName: "codex",
				message,
			});
			if (context?.strict) {
				errors.push({
					artifactName: artifact.name,
					harnessName: "codex",
					message,
					field: "AGENTS.md",
				});
			}
		}
	}

	return { files, warnings, errors: errors.length > 0 ? errors : undefined };
};
